### ISSUE TITLE
開発ドキュメントに誤字あり

### ISSUE THREAD

**Issue by KunimitsuMasuda** [terasoluna-batch/v5-guideline#1]
## Description
誤字がありました。
章節:ジョブの構成要素:ステップ
(誤)バッチ処理を制御をるために
(正)バッチ処理を制御するために
<URL>
https://terasoluna-batch.github.io/guideline/5.0.0.RELEASE/ja/Ch02_TerasolunaBatchArchitecture.html#Ch02_TerasolunaBatchArch_Overview_Step

## Possible Solutions
上記の通り

## Affects Version/s
* 5.0.0RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

## ChangeLog
(To be written later by project member)

**Comment by hosoitk** [comment]
ご指摘ありがとうございます。
`Tag: 5.0.1.RELEASE`で改善しました。
