### ISSUE TITLE
More various database access with ItemWriter

### ISSUE THREAD

**Issue by ikeyat** [terasoluna-batch/v5-guideline#10]
## Description
https://terasoluna-batch.github.io/guideline/5.0.0.RELEASE/ja/single_index.html#Ch05_DBAccess_HowToUse_Input
現在上記では、チャンクモデルでItemWriterでDB書き込みをしたい場合はMyBatisBatchItemWriter一択のように見えてしまうが、MyBatisBatchItemWriterだと制約が多い（よくある例ですと、1入力データに対して２テーブルのレコードを更新することが素直にできない、など）と思います。

それらの制約を回避するための手段はいくつかあると思いますので、紹介したほうが助かる人が多いと思われます。

## Possible Solutions
* CompositeItemWriterを使う  
    * https://terasoluna-batch.github.io/guideline/5.0.0.RELEASE/ja/single_index.html#Ch06_RerunRestart_HowToUse_Restart_Statefull で登場している（6.3.2.4. ステートフルリスタートとは直接関係なさそうですが）。
    * この方法であれば、DBと同時にファイルにも同じデータを出力したいといった要件にも応用できる。
* 自前のItemWriterを使ってデータアクセスを開発者が実装
* ほかに案があれば

## Affects Version/s
* 5.0.0.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

## ChangeLog
(To be written later by project member)

**Comment by hosoitk** [comment]
ご指摘ありがとうございます。
`Tag: 5.0.1.RELEASE`で改善しました。
