### ISSUE TITLE
Minor error, incorrect word

### ISSUE THREAD

**Issue by hayashiyum** [terasoluna-batch/v5-guideline#11]
## Description
[https://terasoluna-batch.github.io/guideline/5.0.0.RELEASE/ja/Ch05_DBAccess.html#Ch05_DBAccess_HowToUse](https://terasoluna-batch.github.io/guideline/5.0.0.RELEASE/ja/Ch05_DBAccess.html#Ch05_DBAccess_HowToUse)
「1. MyBatis用のItemReaderおよびItemReaderを利用する。」がItemReaderおよびItemReaderになっていますが、正しくは「ItemReaderおよびItemWriter」と思います。

## Possible Solutions
上記の通り。

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

## ChangeLog
(To be written later by project member)

**Comment by hosoitk** [comment]
ご指摘ありがとうございます。
`Tag: 5.0.1.RELEASE`で改善しました。
