### ISSUE TITLE
Default value of FlatFileItemWriter#encoding is wrong

### ISSUE THREAD

**Issue by kazuki43zoo** [terasoluna-batch/v5-guideline#12]
## Description
「JavaVMのデフォルト文字セット」となっていますが、実際は「UTF-8」です。

## Possible Solutions
* 「UTF-8」にする（実体に合わせる）
* （全量を確認したわけではないですが、）Readerは「JavaVMのデフォルト文字セット」、Wirterは「UTF-8」になっていそうなので、Spring Batch側にIssueをあげて意図的な違いなのか確認する

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* https://terasoluna-batch.github.io/guideline/5.0.0.RELEASE/ja/Ch05_FileAccess.html#Ch05_FileAccess_VariableLength_Output

## ChangeLog
(To be written later by project member)

**Comment by hosoitk** [comment]
ご指摘ありがとうございます。
`Tag: 5.0.1.RELEASE`で改善しました。
