### ISSUE TITLE
Clerical error in the caption for multi-format example

### ISSUE THREAD

**Issue by ikeyat** [terasoluna-batch/v5-guideline#3]
## Description
https://terasoluna-batch.github.io/guideline/5.0.0.RELEASE/ja/single_index.html#Ch05_FileAccess_Overview_FileType

> シングルフォーマット、レコード区分ありのフラットファイル(CSV形式)の例

は話の流れ的に、おそらくシングルフォーマットでなくマルチフォーマットの例だと思われる。

## Possible Solutions
同上

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

## ChangeLog
(To be written later by project member)

**Comment by hosoitk** [comment]
ご指摘ありがとうございます。
`Tag: 5.0.1.RELEASE`で改善しました。
