### ISSUE TITLE
Target file to be locked is unclear

### ISSUE THREAD

**Issue by ikeyat** [terasoluna-batch/v5-guideline#6]
## Description
https://terasoluna-batch.github.io/guideline/5.0.0.RELEASE/ja/single_index.html#Ch05_ExclusiveControl_HowToUse_File
この例では、(1)Readerで読み込みファイルをロックしているのか、(2)Writerで書き込むファイルをロックしているのか、(3)それらとは別の第三のファイルをロックしているのかが読み取れなかった。
また、もし(1)や(2)がロック対象だとしたら、ReaderやWriterでopenする前にロック取得する例のほうが安全のように思えました。

## Possible Solutions
* 例で示しているロック対象のファイルが何かを明記する。
* 必要に応じてロック取得タイミングの修正を検討する。

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

## ChangeLog
(To be written later by project member)

**Comment by ikeyat** [comment]
コード解説の(2)でwriter.open()を指しているので、issue本文の(2)なので、ロック対象はクリアでした。失礼しました。
タイミングの妥当性についてはご検討お願いします。

**Comment by hosoitk** [comment]
ご指摘ありがとうございます。
`Tag: 5.0.1.RELEASE`で改善しました。
