### ISSUE TITLE
Typo NowWaitLock

### ISSUE THREAD

**Issue by ikeyat** [terasoluna-batch/v5-guideline#7]
## Description
https://terasoluna-batch.github.io/guideline/5.0.0.RELEASE/ja/single_index.html#Ch05_ExclusiveControl_HowToUse_DB_PessimisticLock

org.terasoluna.batch.functionaltest.ch05.exclusivecontrol.repository.ExclusiveControlRepository.branchFindOneWithNowWaitLock

NoWaitLock
のタイポだと思われます。

## Possible Solutions
上記の通り。

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

## ChangeLog
(To be written later by project member)

**Comment by hosoitk** [comment]
Thank you for your advice.
We improved it in `Tag: 5.0.1.RELEASE`.
