### ISSUE TITLE
Minor typos in some chapters

### ISSUE THREAD

**Issue by ynojima** [terasoluna-batch/v5-guideline#8]
Hi, I found some minor Japanese errors. I'll send a pull-request later.

## Description

- 非同実行→非同期実行
- JobExecutionと同様に、Step内でデータを共有するための領域ExecutionCotnextがある。
↓
JobExecutionと同様に、Step内でデータを共有するための領域としてExecutionCotnextがある。
- JobInstanceがユニークにするためだけの引数→JobInstanceをユニークにするためだけの引数
- データベーステーブルの多くは、バージョンカラムが含まれてる
↓
データベーステーブルの多くは、バージョンカラムが含まれている
- CommandLineJonRunner→CommandLineJobRunner
- javaコマンドの終了コードをハンドリングは→javaコマンドの終了コードのハンドリングは
- 以下のような状況に応じてこれを選択可能してよい→以下のような状況に応じてこれを選択してよい
- satrt→start
- 補足→捕捉
- ジョブスコープの実行テキストー>実行コンテキスト

## Possible Solutions

As written above

## Affects Version/s
* 5.0.0.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

## ChangeLog
(To be written later by project member)

**Comment by hosoitk** [comment]
Thank you for your advice.
We improved it in `Tag: 5.0.1.RELEASE`.
